baseURL = "/"
title = "Badge.team"

enableRobotsTXT = true
canonifyURLs = true

theme = ["docsy"]

enableGitInfo = true

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true

[taxonomies]
tag = "tags"
category = "categories"

[params.taxonomy]
taxonomyCloud = ["tags", "categories"]
taxonomyCloudTitle = ["Tag Cloud", "Categories"]
taxonomyPageHeader = ["tags", "categories"]

pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[languages]
[languages.en]
title = "Badge.team"
languageName ="English"
weight = 1
[languages.en.params]
description = "Badges and badgers"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "tango"

[outputs]
section = ["HTML", "print", "RSS"]

[params]
copyright = ""
privacy_policy = ""
version_menu = "Releases"
archived_version = false
version = "0.0"
url_latest_version = "https://badge.team"
github_repo = "https://github.com/badgeteam/website"
github_project_repo = "https://github.com/badgeteam/feedback"
github_branch = "master"

algolia_docsearch = false
offlineSearch = true
prism_syntax_highlighting = false

[params.ui]
breadcrumb_disable = false
footer_about_disable = false
navbar_logo = true
navbar_translucent_over_cover_disable = false
sidebar_menu_compact = false
sidebar_search_disable = false
sidebar_menu_foldable = true

[params.ui.feedback]
enable = false

[params.ui.readingtime]
enable = false

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
  name = "Hatchery"
  url = "https://hatchery.badge.team"
  icon = "fa fa-shopping-bag"
  desc = ""
[[params.links.user]]
  name ="Mastodon"
  url = "https://hsnl.social/@badgeteam"
  icon = "fab fa-mastodon"
  desc = "Follow us on Mastodon to get the latest news!"
[[params.links.user]]
	name = "Telegram chat group"
	url = "https://t.me/+StQpEWyhnb96Y88p"
	icon = "fab fa-telegram"
  desc = "Get in contact"
#[[params.links.user]]
#	name = "Discord chat group"
#	url = "https://discord.gg/xuhw3Ws6BJ"
#	icon = "fab fa-discord"
#  desc = "Get in contact"
[[params.links.developer]]
  name = "GitHub"
  url = "https://github.com/badgeteam"
  icon = "fab fa-github"
  desc = "Source code and design files"
